sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add
  -
- sudo sh -c 'echo "deb http://opensource.wandisco.com/debian/ wheezy svn17" > /etc/apt/sources.list.d/wandisco-subversion.list'
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - MX_APP_NAME=texteditorwidget
  - MX_BRANCH_NAME=trunk
  - MX_PROJECT_ID=8648ccda-9281-4768-abb2-8ce61a80e2f1
  - secure: KSPFU6eNfvMiyKlLlrDw2eYoihJuvEDkHXD8pjbHz5SH23PXeVh2kHXvo8f/Wg+zeYDgGv4bujziW/IvspWboH1VUXHwZM9DLkyJlbeAPSYcI0GtN4eOKmpVnmE6RYv2UiZSPFdRGIGrP0zw/3oLQwHIxOqfHZV3y8xYFA7OFnFsam/I8Qe52ZlTee030472PTA+7D5PP8ltkJUoM6KjNcGa4PBQLLbib5e9n0fk44ORZM5WhawYURkZgsrDmlO3DKYFO8nPMGpz3x6jkbxAvKAQue37i3sohOFofVOm7XJYZsFOQN26xhI4v0I53DWdCJtfiCQ6rjYibUbeJZQpPpcSKw4Q8tV00O/6RSjG8vD4jF4ZyaHlBholl/O3NPmG9Fxe9V3Oyd0ndELaa/fIX5Zxda9J5uzOEvRkZN5LAxBaXuCLvqYoHhaAXeq7kzBCcqTdHwxtVYu8ARGLlAI5djGNZdRDPbMbY/BJpyv1K8QDN+1pulFNUms+upNOHUXX2s9Xdrm2vpM8whK/9JbW7xBpX8Le0siskTUoKb7lkPWOiUizXSuIQmGaysb7N4ROkxdwtw9ztEMUF1utwblPK8DR8a5z+oTI8GlVFkhvAcBUFGv0S/Ec5b99X9QwyOyJJcRfHYeFGmA0Xef6rDiI61rYcRJ4NBfX24WkM6zyDR0=
  - MX_ENVIRONMENT=Sandbox
  - MX_USER=ci@flockofbirds.nl
  - secure: KIkK1pbQfCmOMpYzseXePIH/LiDYKV0jluep4LCsTcpSXzUeaqmTSc8vU4c1AB2UWA48d9lGs+mDYBiLuhsFHWThRVOUDaM+VVAcQIYFhdeSt3UdulPdTkQgvCPEoLnQAwrp6YyDTxSTO6YZReUzeMXvWvZHLBbPm8yJ/Sa2ggWHt5B1MtZ7fZ9IKI6C1L9DjXMTUff1DfqAff5hsgQLaaDRJzaisBi1aH+a4DHppt0OpX9YrkbypJUKiVI9nB7LC6qvXo87ekU9qhKll3MMZCD/AU6siox9pQKx/x3nqoCfQFvrR9q7/awNbshZUTIxhmqPv13pSo4OWVDdYzXB1jeGqauQKWD0TWMhLZ2YRMCXv6rCjF34hGBjU75NejgQ3FYxiTi7Tlvr//J0ixeFKyS0GgbC9Dql5xjeAFeUJz8pfC63zmTsVW21HsvO0N1vclvVl0BnR3F8KB4TQD9EjAyrXK8lvpCJSG3CrgV31AjgbA7OIHOA1x74rd8Sm6S2a4gi7Breys9zOJmqD0h+c9QhrMmUks2NYMnLZj1GoofA348FiOP6ZUEYEMewfK6RwFwjRSXvkFajs1z3GtNWr7PAa9LKGS2GXbwUGiZCVBzgdtI6aUl2xuQJjf4WvhS37UlzUnZ5F6X3x1RnCabSACB/7TnAU260kdOT/k+p4UI=
  deploy: 
  provider: releases
  api_key:
    secure: jkZxWr+Crfkvth5sYDuX3r/TAjGW4YTddRe41jHu9Znubo2wM7i0qAK3ByoWEQMJdyFZbYhNQVXV5JpsXH+7/NlNkOHb7SLPqrWhVGsBNSUjzWXXrJp6TJQlc1PMh/DwGxWG/Q6TQ1SyHVTAEDoi+VDXD4jV1d5pGNXrA7D/ShN5eLGs7sktl9KhBAFKfABkBGHnz1QLw8AFvtLGI7iSOVMpOhbSAxLj20NYR+cBhgx7DPGJ5Cnp5Huhz7ky75WPtdd79H0bWCZFyE01BuDnsm5Bp/W87Pg9vsIaD1WWdfdrzucxFVSaKsjC42I5/ILretlPl0Y+UO/Km3MZIch6YfIB+p7TrIn4R6qXTKdnFtW40R0ziu2UpcFCW2KV0P0rOZojPs9u/r2pxJdz/b0UDQP5hMwJoj/0R2V9VLHs24kUSystmu1wKSJVC9j74RhZJxVzO/SAUtfULHqLqINrd9ewcct163KzTq4blVDHn/5F/2Lj5r/Gkn3Qp9tdjPBwntVt46Z+tFK2fuwZ6RNkyHJVsQcyu0OS8YYxLHW1vAmK7qiwANcywn2tg7Q8KflZE04yqh3Buv1x9cLoS5BiUncS+YXuPH0M/u8pUR/fc6EEofo0PhYlndn2/xrnniunD+VYcjtD2aMjCSiHz2wmGLQGT5VOqL0xblDcxQASVvg=
  file_glob: true
  file: dist/release/*
  skip_cleanup: true
  on:
    repo: FlockOfBirds/rich-text
    tags: true
